version: "3.7"

services:

  flask:
    build: ./src/flask
    container_name: flask
    restart: always
    environment:
      - FLASK_APP=run.py
      - FLASK_DEBUG=1
    expose:
      - 8080
    ports:
      - 8119:8080

  nginx:
    build: ./src/nginx
    container_name: nginx
    restart: always
    depends_on:
      - flask
    ports:
      - "8120:80"

  mlflow:
    restart: always
    image: mlflow_server
    container_name: mlflow_server
    environment:
      - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
    ports:
      - "5000:5000"
    depends_on:
      - flask
    command: mlflow server --host 0.0.0.0 --default-artifact-root mlruns