version: "3.7"

services:

  flask:
    build: ./src/flask
    container_name: flask
    restart: always
    environment:
      - FLASK_APP=run.py
      - FLASK_DEBUG=1
    expose:
      - 8080
    ports:
      - 8119:8080

  nginx:
    build: ./src/nginx
    container_name: nginx
    restart: always
    depends_on:
      - flask
    ports:
      - "8120:80"