version: "3.7"

services:

  flask:
    build: ./src/server/flask
    container_name: flask
    restart: always
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
    expose:
      - 8080

  nginx:
    build: ./src/server/nginx
    container_name: nginx
    restart: always
    depends_on:
      - flask
    ports:
      - "80:80"